. "$PSScriptRoot\Core\Commands\Get-AbsolutePath\Get-AbsolutePath.Cmd.ps1"
. "$PSScriptRoot\Core\Commands\Sudo\Sudo.Cmd.ps1"

. "$PSScriptRoot\Core\Functions\Function.ps1"
. "$PSScriptRoot\Core\Functions\Color.ps1"
. "$PSScriptRoot\Core\Functions\Base64.ps1"
. "$PSScriptRoot\Core\Functions\Git.ps1"
. "$PSScriptRoot\Core\Functions\Env.ps1"
. "$PSScriptRoot\Core\Functions\Module.ps1"
. "$PSScriptRoot\Core\Functions\PowerShell.ps1"
. "$PSScriptRoot\Core\Functions\Admin.ps1"
. "$PSScriptRoot\Core\Functions\PipelineWatch.ps1"

. "$PSScriptRoot\Core\Extensions\Zoxide.ps1"
. "$PSScriptRoot\Core\Extensions\PoshGit.ps1"
. "$PSScriptRoot\Core\Extensions\NPM.ps1"

. "$PSScriptRoot\Core\Configs\PSReadLine.ps1"
. "$PSScriptRoot\Core\Configs\Alias.ps1"
. "$PSScriptRoot\Core\Configs\Env.ps1"